/* eslint-disable max-len */
export const BLUR_IMAGE_URL = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA8AAAARCAYAAAACCvahAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAjSURBVDhPY7x169J/BjIBE5QmC4xqJhGMaiYRjGomCTAwAACCfQOnJx9CEAAAAABJRU5ErkJggg==";
export const USER_COOKIE_KEY = "dofu/user";